hpc_determining_command: "squeue"  # If this command is found, treat machine as HPC

# Determine job run time and resources
job_partition: "smp"
job_memory: "12GB"
job_walltime_limit: "24:00:00"
job_cpus_per_task: 1
job_conda_env: "Barry"
